# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  fr: BleRiFa
  en: BleRiFa
email: contact@julienduroure.com
description:
  en: BleRiFa is a toolset to simplify your rigging life !
  fr: BleRiFa est une boite à outils pour le Rigging et l'Animation !
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://julienduroure.github.io/BleRiFa" # the base hostname & protocol for your site
index:
  en: /
  fr: /fr/
twitter_username: julienduroure
github_username:  julienduroure
analytics: false #false or UA_ID
copyright: "&copy 2016 Julien Duroure / BleRiFa"

# Build settings
markdown: kramdown

exclude: [Gemfile, Gemfile.lock, _BleRiFa_template/]

collections:
  banners:
    output: false
  tools:
    output: true
  quick:
    output: true

