# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BleRiFa
email: contact@julienduroure.com
description: > # this means to ignore newlines until "baseurl:"
  BleRiFa is a toolset to simplify your rigging life !
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://julienduroure.github.io/BleRiFa" # the base hostname & protocol for your site
index:
	en: /
	fr: /fr/
twitter_username: julienduroure
github_username:  julienduroure

# Build settings
markdown: kramdown
